# Generated by Django 4.0.4 on 2022-08-07 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_appuserlv1profile_appuserlv2profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Enterprise',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.enterprise'),
        ),
    ]
