# Generated by Django 4.0.4 on 2022-12-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_product_category_product_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solped',
            old_name='owner',
            new_name='user',
        ),
    ]
