# Generated by Django 4.0.4 on 2022-08-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPPLIER', 'Supplier'), ('USUARIO', 'AppUserLv1'), ('USUARIOAUTH', 'AppUserLv2'), ('COMPRADORNEGOCIADOR', 'AppUserLv3')], max_length=50),
        ),
    ]
