# Generated by Django 4.0.4 on 2022-08-08 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('taxPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('shippingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('tiempoDeEntrega', models.DateTimeField(blank=True, null=True)),
                ('garantia', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solped', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order')),
            ],
        ),
    ]
