# Generated by Django 4.0.4 on 2022-08-08 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='solped',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order'),
        ),
    ]
